name: Sync With Upstream
on:
  schedule:
    - cron: '0 0/12 * * *' # sync twice every day at noon and midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get full commit history

      - name: Add Upstream
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_URL }}
          git fetch upstream

      - name: Merge Changes
        run: |
          git checkout master
          git merge upstream/master --no-edit
          git push origin master