name: Sync With Upstream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16,4 * * *' # sync twice every day at noon and midnight, due to UTC timezone convertion, minus 8

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Sync upstream changes
        run: |
          git clone https://${{ secrets.ACTION_TOKEN }}@github.com/${{ github.repository }}.git tmp
          cd tmp
          git config user.name SurpassHR
          git config user.email hu.rui0530@gmail.com
          git remote add upstream https://${{ secrets.ACTION_TOKEN }}@github.com/comfyanonymous/ComfyUI.git
          git fetch upstream
          git merge upstream/master
          git push origin master

      # - name: Push Changes
      #   run: git push https://github.com/${{ github.repository }}.git HEAD:master