name: Sync With Upstream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16/12 * * *' # sync twice every day at noon and midnight, due to UTC timezone convertion, minus 8

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get full commit history

      - name: Add Upstream
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_URL }}
          git fetch upstream

      - name: Config Git Info
        run: |
          git config user.name SurpassHR
          git config user.email hu.rui0530@gmail.com

      - name: Merge Changes
        run: |
          git checkout master
          git merge upstream/master --no-edit
          git push origin master